excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - job-readiness/AppDelegate.swift
  - job-readiness/SceneDelegate.swift

disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
